### ISSUE TITLE
smb.conf still has default parameters

### ISSUE THREAD

**Issue by stevland** [dnlongen/ASUSWRT_Samba_Fixer#1]
This is awesome @dnlongen , thank you for your detailed explanation and instructions.

But I can't seem to get it working with my ASUS RT-AC55U _(FW:3.0.0.4.380_3264)_.

I created a file called `testme` and added the following line to `fixsamba`:

`cp /jffs/testme /etc/`

Upon reboot, I have confirmed that `testme` has been copied from `/jffs` to `/etc`.

When I look at `/etc/smb.conf`, however, it contains the factory parameters.

I am wondering if `smb.conf` is failing to copy, or if it is subsequently being rewritten by another process.

Any tips?

---

P.S. I believe there is a small miswording in your README.md.

> Modify smb.conf to suit your preference, then store to /jffs
> 
> `chmod 644 /jffs/fixsamba`

I'm pretty sure this was meant to be

`chmod 644 /jffs/smb.conf`, yeah?

**Comment by dnlongen** [comment]
First the P.S. - thanks, you are correct. That's now fixed :-)

Now your actual question: it appears either the smb.conf file is being overwritten when the service stops, or the permissions are not set properly on the copied file. I made the following changes on my local router, and updated fixsamba in this repo and it works again:

After killing the smbd process, wait 3 minutes

Copy the smb.conf file from /jffs to /etc/ AFTER the 3 minute wait
Set the permissions on the newly-copied /etc/smb.conf to 444.

**Comment by stevland** [comment]
It works! Thank you.

**Comment by stevland** [comment]
I also noticed that after killing `smbd`on my router, my shares where still available on the network by IP address.

I also had to kill `nmbd`.

I then got distracted before I had time to investigate further, but I was wondering if this was related to my issue.

Anyway, the solution you've come up with is great. Cheers.
